CXX= g++
CFLAGS= -Wall -g -std=c++11
OBJS= xor.o crypteur.o test_xor.o
EXEC= test_xor

.PHONY: clean

$(EXEC): $(OBJS)
	$(CXX) -o $@ $^

%.o: %.cxx
	$(CXX) $(CFLAGS) -c $<

clean:
	$(RM) *.o $(EXEC)