CXX= g++
CFLAGS= -Wall -g -std=c++11
OBJS= crypteur.o testcryp.o
EXEC= testcryp

.PHONY: clean

$(EXEC): $(OBJS)
	$(CXX) -o $@ $^

%.o: %.cxx
	$(CXX) $(CFLAGS) -c $<

clean:
	$(RM) *.o $(EXEC)