CXX= g++
CFLAGS= -Wall -g -std=c++11
OBJS= src/compress.o src/testcomp.o
EXEC= testcomp

.PHONY: clean

$(EXEC): $(OBJS)
	$(CXX) -o $@ $^

src/%.o: src/%.cxx
	$(CXX) $(CFLAGS) -o $@ -c $<

clean:
	$(RM) *.o $(EXEC)