@startuml

namespace compression {

class RleCompressor {
   -int threshold_;
   -int repetitionCode_;
   -float rate_;
   +RleCompressor(int threshold, int repetitionCode);
   +~RleCompressor();
   +int getThreshold() const;
   +int getRepetitionCode() const;
   +float getRate() const;
   +void setThreshold(const int threshold);
   +void setRepetitionCode(const int repetitionCode);
   +void compress(string inputfile, string outputfile);
   +void decompress(string inputfile, string outputfile);
   +friend ostream &operator<<(ostream &os, Compressor &compressor);
   +friend istream &operator>>(istream &is, Compressor &compressor);
}

RleCompressor "1" *-right- "2" fstream: flux

}

@enduml